### ISSUE TITLE
支持

### ISSUE THREAD

**Issue by PlainsVillager** [Jaffe2718/Fabric-Sniper-Rifle-1.19.2-MDK#3]
文档很详细，很可以
up能点评一下我的Mod吗（逃）

**Comment by Jaffe2718** [comment]
> 文档很详细，很可以 up能点评一下我的Mod吗（逃）

欢迎大佬光临
请问你的模组是在couseforge还是GitHub上面？

**Comment by PlainsVillager** [comment]
> > 文档很详细，很可以 up能点评一下我的Mod吗（逃）
> 
> 欢迎大佬光临 请问你的模组是在couseforge还是GitHub上面？

别叫我大佬，我就是个傻宝（
https://modrinth.com/mod/anti-creeper

**Comment by Jaffe2718** [comment]
> > > 文档很详细，很可以 up能点评一下我的Mod吗（逃）
> > 
> > 
> > 欢迎大佬光临 请问你的模组是在couseforge还是GitHub上面？
> 
> 别叫我大佬，我就是个傻宝（ https://modrinth.com/mod/anti-creeper

OK，已经点赞啦
